name: "Build and Publish Docker Image"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created  # Triggers on GitHub Releases

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Determine Image Name and Version
    - name: Set up Docker Image Variables
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/portainer-service-webhook"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG="latest"
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    # Step 4: Build and tag Docker image
    - name: Build and tag Docker image
      run: |
        docker build -t $IMAGE_NAME:$TAG .
        docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

    # Step 5: Push the Docker image with version tag
    - name: Push Docker image with version tag
      run: docker push $IMAGE_NAME:$TAG
