name: Release GitHub Action

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Bundle Action with NCC
        run: |
          npm install -g @vercel/ncc
          ncc build index.js -o dist

      - name: Temporarily Commit dist/ for Tagging
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout main
          git add dist/ -f
          git commit -m "build: prepare action for release" || echo "No changes to commit"
          git push origin main

      - name: Retag and Push Updated Tag
        run: |
          git tag -d ${{ github.ref_name }} || echo "Tag does not exist"
          git push --delete origin ${{ github.ref_name }} || echo "No remote tag to delete"
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove dist/ from Main Branch After Tagging
        run: |
          git rm -r --cached dist/
          git commit -m "build: cleanup dist after release" || echo "Nothing to remove"
          git push origin main